// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "avito_backend_task/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

// AssignReviewer provides a mock function with given fields: ctx, prID, reviewerID
func (_m *PullRequestRepository) AssignReviewer(ctx context.Context, prID string, reviewerID string) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for AssignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePullRequest provides a mock function with given fields: ctx, pr
func (_m *PullRequestRepository) CreatePullRequest(ctx context.Context, pr domain.PullRequestCreate) (time.Time, error) {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PullRequestCreate) (time.Time, error)); ok {
		return rf(ctx, pr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PullRequestCreate) time.Time); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PullRequestCreate) error); ok {
		r1 = rf(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exists provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) Exists(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPullRequestByID provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) GetPullRequestByID(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByID")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsReviewerAssigned provides a mock function with given fields: ctx, prID, userID
func (_m *PullRequestRepository) IsReviewerAssigned(ctx context.Context, prID string, userID string) (bool, error) {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsReviewerAssigned")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, prID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, prID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergePullRequest provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) MergePullRequest(ctx context.Context, prID string) error {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveReviewer provides a mock function with given fields: ctx, prID, reviewerID
func (_m *PullRequestRepository) RemoveReviewer(ctx context.Context, prID string, reviewerID string) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
